### ISSUE TITLE
TypeError: error.getFile is not a function

### ISSUE THREAD

**Issue by liangchunn** [liangchunn/typescript-node-scripts#62]
Originally reported by @angelsvirkov, TNS crashes when there is a linting error with version `v1.0.6`
This is caused by `fork-ts-webpack-checker-plugin@0.5.0`, and fixed in version `0.5.1`.

This issue has already been fixed with #61 , and a new version of TNS has to be published.

```
Starting the development server...
Using TypeScript v3.2.1
/Users/liangchun/typescript-node-scripts/lib/formatForkTsCheckerMessages.js:9
    const file = error.getFile()
                       ^

TypeError: error.getFile is not a function
    at ForkTsCheckerWebpackPlugin.formatter (/Users/liangchun/typescript-node-scripts/lib/formatForkTsCheckerMessages.js:9:24)
    at diagnostics.concat.forEach.message (/Users/liangchun/typescript-node-scripts/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:533:35)
    at Array.forEach (<anonymous>)
    at ForkTsCheckerWebpackPlugin.emitCallback (/Users/liangchun/typescript-node-scripts/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:525:49)
    at ForkTsCheckerWebpackPlugin.handleServiceMessage (/Users/liangchun/typescript-node-scripts/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:488:72)
    at ChildProcess.service.on (/Users/liangchun/typescript-node-scripts/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:429:54)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by liangchunn** [comment]
Closed with `v1.0.7` in 155f614
